USER ={
   "user":{
      "properties":{
         "aboutMe":{
            "type":"string"
         },
         "address":{
            "type":"object",
            "properties":{
               "city":{
                  "type":"string"
               },
               "country":{
                  "type":"string"
               },
               "state":{
                  "type":"string"
               },
               "street":{
                  "type":"string"
               },
               "zip":{
                  "type":"string"
               }
            }
         },
         "chatterActivity":{
            "type":"object",
            "properties":{
               "commentCount":{
                  "type":"integer"
               },
               "commentReceivedCount":{
                  "type":"integer"
               },
               "likeReceivedCount":{
                  "type":"integer"
               },
               "postCount":{
                  "type":"integer"
               }
            }
         },
         "chatterInfluence":{
            "type":"object",
            "properties":{
               "percentile":{
                  "type":"string"
               },
               "rank":{
                  "type":"integer"
               }
            }
         },
         "companyName":{
            "type":"string"
         },
         "currentStatus":{
            "type":"object",
            "properties":{
               "body":{
                  "type":"object",
                  "properties":{
                     "messageSegments":{
                        "type":"array",
                        "items":[

                        ]
                     },
                     "text":{
                        "type":"string"
                     }
                  }
               },
               "parentId":{
                  "type":"string"
               },
               "url":{
                  "type":"string"
               }
            }
         },
         "email":{
            "type":"string"
         },
         "firstName":{
            "type":"string"
         },
         "followersCount":{
            "type":"integer"
         },
         "followingCounts":{
            "type":"object",
            "properties":{
               "people":{
                  "type":"integer"
               },
               "records":{
                  "type":"integer"
               },
               "total":{
                  "type":"integer"
               }
            }
         },
         "groupCount":{
            "type":"integer"
         },
         "id":{
            "type":"string"
         },
         "isActive":{
            "type":"boolean"
         },
         "isChatterGuest":{
            "type":"boolean"
         },
         "lastName":{
            "type":"string"
         },
         "managerId":{
            "type":"string"
         },
         "managerName":{
            "type":"string"
         },
         "mySubscription":{
            "type":"string"
         },
         "name":{
            "type":"string"
         },
         "phoneNumbers":{
            "type":"array",
            "items":[

            ]
         },
         "photo":{
            "type":"object",
            "properties":{
               "largePhotoUrl":{
                  "type":"string"
               },
               "photoVersionId":{
                  "type":"string"
               },
               "smallPhotoUrl":{
                  "type":"string"
               }
            }
         },
         "title":{
            "type":"string"
         },
         "type":{
            "type":"string"
         },
         "url":{
            "type":"string"
         },
         "username":{
            "type":"string"
         }
      }
   }
}

ACCOUNT ={
   "account":{
      "properties":{
         "Id":{
            "type":"string"
         },
         "IsDeleted":{
            "type":"boolean"
         },
         "MasterRecordId":{
            "type":"string"
         },
         "Name":{
            "type":"string"
         },
         "Type":{
            "type":"string"
         },
         "ParentId":{
            "type":"string"
         },
         "BillingStreet":{
            "type":"string"
         },
         "BillingCity":{
            "type":"string"
         },
         "BillingState":{
            "type":"string"
         },
         "BillingPostalCode":{
            "type":"string"
         },
         "BillingCountry":{
            "type":"string"
         },
         "ShippingStreet":{
            "type":"string"
         },
         "ShippingCity":{
            "type":"string"
         },
         "ShippingState":{
            "type":"string"
         },
         "ShippingPostalCode":{
            "type":"string"
         },
         "ShippingCountry":{
            "type":"string"
         },
         "Phone":{
            "type":"string"
         },
         "Fax":{
            "type":"string"
         },
         "AccountNumber":{
            "type":"string"
         },
         "Website":{
            "type":"string"
         },
         "Sic":{
            "type":"string"
         },
         "Industry":{
            "type":"string"
         },
         "AnnualRevenue":{
            "type":"integer"
         },
         "NumberOfEmployees":{
            "type":"integer"
         },
         "Ownership":{
            "type":"string"
         },
         "TickerSymbol":{
            "type":"string"
         },
         "Description":{
            "type":"string"
         },
         "Rating":{
            "type":"string"
         },
         "Site":{
            "type":"string"
         },
         "OwnerId":{
            "type":"string"
         },
         "CreatedDate":{
            "type":"string"
         },
         "CreatedById":{
            "type":"string"
         },
         "LastModifiedDate":{
            "type":"string"
         },
         "LastModifiedById":{
            "type":"string"
         },
         "SystemModstamp":{
            "type":"string"
         },
         "LastActivityDate":{
            "type":"string"
         },
         "CustomerPriority__c":{
            "type":"string"
         },
         "SLA__c":{
            "type":"string"
         },
         "Active__c":{
            "type":"string"
         },
         "NumberofLocations__c":{
            "type":"integer"
         },
         "UpsellOpportunity__c":{
            "type":"string"
         },
         "SLASerialNumber__c":{
            "type":"string"
         },
         "SLAExpirationDate__c":{
            "type":"string"
         }
      }
   }
}

OPPORTUNITY ={
   "opportunity":{
      "properties":{
         "Id":{
            "type":"string"
         },
         "IsDeleted":{
            "type":"boolean"
         },
         "AccountId":{
              "type":"string"
         },
         "IsPrivate":{
            "type":"boolean"
         },
         "Name":{
            "type":"string"
         },
         "Description":{
            "type":"string"
         },
         "StageName":{
            "type":"string"
         },
         "Amount":{
            "type":"string"
         },
         "Probability":{
            "type":"integer"
         },
         "ExpectedRevenue":{
            "type":"string"
         },
         "TotalOpportunityQuantity":{
            "type":"string"
         },
         "CloseDate":{
            "type":"string"
         },
         "Type":{
            "type":"string"
         },
         "NextStep":{
            "type":"string"
         },
         "LeadSource":{
            "type":"string"
         },
         "IsClosed":{
            "type":"boolean"
         },
         "IsWon":{
            "type":"boolean"
         },
         "ForecastCategory":{
            "type":"string"
         },
         "ForecastCategoryName":{
            "type":"string"
         },
         "CampaignId":{
            "type":"string"
         },
         "HasOpportunityLineItem":{
            "type":"boolean"
         },
         "Pricebook2Id":{
            "type":"string"
         },
         "OwnerId":{
            "type":"string"
         },
         "CreatedDate":{
            "type":"string"
         },
         "CreatedById":{
            "type":"string"
         },
         "LastModifiedDate":{
            "type":"string"
         },
         "LastModifiedById":{
            "type":"string"
         },
         "SystemModstamp":{
            "type":"string"
         },
         "LastActivityDate":{
            "type":"string"
         },
         "FiscalQuarter":{
            "type":"integer"
         },
         "FiscalYear":{
            "type":"integer"
         },
         "Fiscal":{
            "type":"string"
         },
         "LastViewedDate":{
            "type":"string"
         },
         "LastReferencedDate":{
            "type":"string"
         },
         "DeliveryInstallationStatus__c":{
            "type":"string"
         },
         "TrackingNumber__c":{
            "type":"string"
         },
         "OrderNumber__c":{
            "type":"string"
         },
         "CurrentGenerators__c":{
            "type":"string"
         },
         "MainCompetitors__c":{
            "type":"string"
         }
      }
   }
}

LEAD = {
   "lead":{
      "properties":{
         "Id":{
            "type":"string"
         },
         "IsDeleted":{
            "type":"boolean"
         },
         "MasterRecordId":{
            "type":"string"
         },
         "LastName":{
            "type":"string"
         },
         "FirstName":{
            "type":"string"
         },
         "Salutation":{
            "type":"string"
         },
         "Name":{
            "type":"string"
         },
         "Title":{
            "type":"string"
         },
         "Company":{
            "type":"string"
         },
         "Street":{
            "type":"string"
         },
         "City":{
            "type":"string"
         },
         "State":{
            "type":"string"
         },
         "PostalCode":{
            "type":"string"
         },
         "Country":{
            "type":"string"
         },
         "Latitude":{
            "type":"string"
         },
         "Longitude":{
            "type":"string"
         },
         "Phone":{
            "type":"string"
         },
         "MobilePhone":{
            "type":"string"
         },
         "Fax":{
            "type":"string"
         },
         "Email":{
            "type":"string"
         },
         "Website":{
            "type":"string"
         },
         "Description":{
            "type":"string"
         },
         "LeadSource":{
            "type":"string"
         },
         "Status":{
            "type":"string"
         },
         "Industry":{
            "type":"string"
         },
         "Rating":{
            "type":"string"
         },
         "AnnualRevenue":{
            "type":"integer"
         },
         "NumberOfEmployees":{
            "type":"string"
         },
         "OwnerId":{
            "type":"string"
         },
         "IsConverted":{
            "type":"boolean"
         },
         "ConvertedDate":{
            "type":"string"
         },
         "ConvertedAccountId":{
            "type":"string"
         },
         "ConvertedContactId":{
            "type":"string"
         },
         "ConvertedOpportunityId":{
            "type":"string"
         },
         "IsUnreadByOwner":{
            "type":"boolean"
         },
         "CreatedDate":{
            "type":"string"
         },
         "CreatedById":{
            "type":"string"
         },
         "LastModifiedDate":{
            "type":"string"
         },
         "LastModifiedById":{
            "type":"string"
         },
         "SystemModstamp":{
            "type":"string"
         },
         "LastActivityDate":{
            "type":"string"
         },
         "LastViewedDate":{
            "type":"string"
         },
         "LastReferencedDate":{
            "type":"string"
         },
         "Jigsaw":{
            "type":"string"
         },
         "JigsawContactId":{
            "type":"string"
         },
         "CleanStatus":{
            "type":"string"
         },
         "CompanyDunsNumber":{
            "type":"string"
         },
         "DandbCompanyId":{
            "type":"string"
         },
         "EmailBouncedReason":{
            "type":"string"
         },
         "EmailBouncedDate":{
            "type":"string"
         },
         "SICCode__c":{
            "type":"string"
         },
         "ProductInterest__c":{
            "type":"string"
         },
         "Primary__c":{
            "type":"string"
         },
         "CurrentGenerators__c":{
            "type":"string"
         },
         "NumberofLocations__c":{
            "type":"integer"
         }
      }
   }
}

TASK = {
   "task":{
      "properties":{
         "Id":{
            "type":"string"
         },
         "WhoId":{
            "type":"string"
         },
         "WhatId":{
            "type":"string"
         },
         "Subject":{
            "type":"string"
         },
         "ActivityDate":{
            "type":"string"
         },
         "Status":{
            "type":"string"
         },
         "Priority":{
            "type":"string"
         },
         "OwnerId":{
            "type":"string"
         },
         "Description":{
            "type":"string"
         },
         "IsDeleted":{
            "type":"boolean"
         },
         "AccountId":{
            "type":"string"
         },
         "IsClosed":{
            "type":"boolean"
         },
         "CreatedDate":{
            "type":"string"
         },
         "CreatedById":{
            "type":"string"
         },
         "LastModifiedDate":{
            "type":"string"
         },
         "LastModifiedById":{
            "type":"string"
         },
         "SystemModstamp":{
            "type":"string"
         },
         "IsArchived":{
            "type":"boolean"
         },
         "CallDurationInSeconds":{
            "type":"string"
         },
         "CallType":{
            "type":"string"
         },
         "CallDisposition":{
            "type":"string"
         },
         "CallObject":{
            "type":"string"
         },
         "ReminderDateTime":{
            "type":"string"
         },
         "IsReminderSet":{
            "type":"boolean"
         },
         "RecurrenceActivityId":{
            "type":"string"
         },
         "IsRecurrence":{
            "type":"boolean"
         },
         "RecurrenceStartDateOnly":{
            "type":"string"
         },
         "RecurrenceEndDateOnly":{
            "type":"string"
         },
         "RecurrenceTimeZoneSidKey":{
            "type":"string"
         },
         "RecurrenceType":{
            "type":"string"
         },
         "RecurrenceInterval":{
            "type":"string"
         },
         "RecurrenceDayOfWeekMask":{
            "type":"string"
         },
         "RecurrenceDayOfMonth":{
            "type":"string"
         },
         "RecurrenceInstance":{
            "type":"string"
         },
         "RecurrenceMonthOfYear":{
            "type":"string"
         }
      }
   }
}

EVENT = {
   "event":{
      "properties":{
         "Id":{
            "type":"string"
         },
         "WhoId":{
            "type":"string"
         },
         "WhatId":{
            "type":"string"
         },
         "Subject":{
            "type":"string"
         },
         "Location":{
            "type":"string"
         },
         "IsAllDayEvent":{
            "type":"boolean"
         },
         "ActivityDateTime":{
            "type":"string"
         },
         "ActivityDate":{
            "type":"string"
         },
         "DurationInMinutes":{
            "type":"integer"
         },
         "StartDateTime":{
            "type":"string"
         },
         "EndDateTime":{
            "type":"string"
         },
         "Description":{
            "type":"string"
         },
         "AccountId":{
            "type":"string"
         },
         "OwnerId":{
            "type":"string"
         },
         "IsPrivate":{
            "type":"boolean"
         },
         "ShowAs":{
            "type":"string"
         },
         "IsDeleted":{
            "type":"boolean"
         },
         "IsChild":{
            "type":"boolean"
         },
         "IsGroupEvent":{
            "type":"boolean"
         },
         "GroupEventType":{
            "type":"string"
         },
         "CreatedDate":{
            "type":"string"
         },
         "CreatedById":{
            "type":"string"
         },
         "LastModifiedDate":{
            "type":"string"
         },
         "LastModifiedById":{
            "type":"string"
         },
         "SystemModstamp":{
            "type":"string"
         },
         "IsArchived":{
            "type":"boolean"
         },
         "RecurrenceActivityId":{
            "type":"string"
         },
         "IsRecurrence":{
            "type":"boolean"
         },
         "RecurrenceStartDateTime":{
            "type":"string"
         },
         "RecurrenceEndDateOnly":{
            "type":"string"
         },
         "RecurrenceTimeZoneSidKey":{
            "type":"string"
         },
         "RecurrenceType":{
            "type":"string"
         },
         "RecurrenceInterval":{
            "type":"string"
         },
         "RecurrenceDayOfWeekMask":{
            "type":"string"
         },
         "RecurrenceDayOfMonth":{
            "type":"string"
         },
         "RecurrenceInstance":{
            "type":"string"
         },
         "RecurrenceMonthOfYear":{
            "type":"string"
         },
         "ReminderDateTime":{
            "type":"string"
         },
         "IsReminderSet":{
            "type":"boolean"
         }
      }
   }
}

PUSH_TOPIC = {
   "push_topic":{
      "properties":{

         "Id":{
            "type":"string"
         },
         "Name":{
            "type":"string"
         },
         "Query":{
            "type":"string"
         },
         "ApiVersion":{
            "type":"integer"
         },
         "IsActive":{
            "type":"boolean"
         },
         "NotifyForFields":{
            "type":"string"
         },
         "NotifyForOperations":{
            "type":"string"
         },
         "Description":{
            "type":"string"
         },
         "NotifyForOperationCreate":{
            "type":"boolean"
         },
         "NotifyForOperationUpdate":{
            "type":"boolean"
         },
         "NotifyForOperationDelete":{
            "type":"boolean"
         },
         "NotifyForOperationUndelete":{
            "type":"boolean"
         },
         "IsDeleted":{
            "type":"boolean"
         },
         "CreatedDate":{
            "type":"string"
         },
         "CreatedById":{
            "type":"string"
         },
         "LastModifiedDate":{
            "type":"string"
         },
         "LastModifiedById":{
            "type":"string"
         },
         "SystemModstamp":{
            "type":"string"
         }
      }
   }
}

MAPPINGS = {'user':USER,
			'account':ACCOUNT,
			'opportunity':OPPORTUNITY,
			'lead':LEAD,
			'task':TASK,
			'event':EVENT
			}

